---

- name: restart_mssql
  service:
    name: mssql-server
    state: restarted
    enabled: yes
  become: yes

- name: restart_fail2ban
  service:
    name: fail2ban
    state: restarted
  become: yes
